Practice1/Models/Repository.cs
namespace MeetingApp.Models
{
    public static class Repository{    

        private static List<UserInfo> _users = new();

        static Repository(){
            _users.Add(new UserInfo(){
                id=1, Name="Ahmet", Email="ahmet@gmail.com", Phone="1234", WillAttend=true
            });
              _users.Add(new UserInfo(){
                id=2, Name="Mehmet", Email="mehmet@gmail.com", Phone="1235", WillAttend=true
            });
              _users.Add(new UserInfo(){
                id=3, Name="Ayse", Email="ayse@gmail.com", Phone="1236", WillAttend=true
            });
        }
        
        public static List<UserInfo> users{
            get{
               return _users;
            }
        }

        public static void CreateUser(UserInfo user){
            user.id = users.Count + 1;
            _users.Add(user);
        }

        public static UserInfo? GetById(int Id){
            return _users.FirstOrDefault(user => user.id == Id);
        }
    }

}

Practice1/Models/UserInfo.cs
using System.ComponentModel.DataAnnotations;

namespace MeetingApp.Models
{
    public class UserInfo
    {
        public int id { get; set; }

        [Required(ErrorMessage = "Name field is required")]
        public string? Name { get; set; }

        [Required(ErrorMessage = "Phone field is required")]
        public string? Phone { get; set; }

        [Required]
        [EmailAddress]
        [RegularExpression(@"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$", ErrorMessage = "The e-mail address is not valid")]
        public string? Email { get; set; }

        [Required]
        public bool? WillAttend { get; set; }
    }
}

Practice1/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MeetingApp.Models;

namespace MeetingApp.Controllers{
    public class HomeController : Controller {

         //localhost..../home/index
        public IActionResult Index(){
            int time = DateTime.Now.Hour;

            //---------------- With Model -----------------
            //var sayHello = time > 12 ? "Good Day" : "Good Morning";            
            //return View(model: sayHello);  

            //---------------- With ViewBag -----------------
            //ViewBag.sayHello = time > 12 ? "Good Day" : "Good Morning";
            //ViewBag.username = "Beyza";
            //ViewBag.dateTime = "system time is: " + time;
            

            //---------------- With ViewData-----------------
            ViewData["hello"] = time > 12 ? "Good Day" : "Good Morning";             
            int usercount = Repository.users.Where(info => info.WillAttend == true).Count();
            ViewBag.NoP = usercount;

            return View();
            
        }
    }
}

Practice1/Controllers/MeetingController.cs
using Microsoft.AspNetCore.Mvc;
using MeetingApp.Models;

namespace MeetingApp.Controllers{
    public class MeetingController : Controller {
        public IActionResult Index(){
            return View();
        }

        [HttpGet]
        public IActionResult Register(){
            return View();
        }

        [HttpPost]
         public IActionResult Register(UserInfo model){
            if(ModelState.IsValid){
                Repository.CreateUser(model);
                ViewBag.UserCount = Repository.users.Where(i=> i.WillAttend==true).Count();            
                return View("RegistrationThanks", model);
            } else{
                return View("Register", model);
            }  
        }
        
        public IActionResult List(){
            return View(Repository.users); 
        }

        public IActionResult Details(int id){
            return View(Repository.GetById(id));
        }

        public IActionResult RegistrationThanks(){
            return View();
        }
    }
}

Practice1/Controllers/MeetingSummaryController.cs
using Microsoft.AspNetCore.Mvc;

namespace MeetingApp.Controllers{
    public class MeetingSummaryController : Controller {

        [Route("/MeetingSummary/Index", Name = "Custom")]
        public IActionResult Index(){
            return View();
        }

        public IActionResult Contact(){
            return View();
        }
    }
}

Practice1/Views/Home/Index.cshtml
@* 
--- With Model ---
@model string 
<h1> Welcome! @Model </h1>
*@

@* 
--- With ViewBag ---
<h1> @ViewBag.sayHello @ViewBag.username </h1>
<h5> @ViewBag.dateTime </h5>
*@


<h1>@ViewData["hello"] Welcome!</h1>

<h2> Register to the meeting by clicking <a href="/Meeting/Register">here.</a></h2>

@Html.ActionLink("About the meeting", "Index", "MeetingSummary")

@Html.ActionLink("Click for the participant list", "List", "Meeting")




@section header {
    <div id="header">
        HOME PAGE
    </div>
}

@section footer {
    <h6> There are @ViewBag.NoP participants in meeting. </h6>
    <h5><a href="/MeetingSummary/Contact">Contact</a></h5>
}

Practice1/Views/Meeting/Details.cshtml
@model UserInfo

<main class="text-start">
    <h4> Participants Details: </h4>
    <p> <b>Name:</b> @Model.Name </p>
    <p> <b>Phone:</b> @Model.Phone </p>
    <p> <b>E-mail:</b> @Model.Email </p>
</main>

Practice1/Views/Meeting/Index.cshtml
<h3>Last years' meetings:</h3>
<table>
    <tr>
        <td>Meeting 2023</td><td><button button-type="submit">click</button></td>
    </tr>
    <tr>
        <td>Meeting 2022</td><td><button button-type="submit">click</button></td>
    </tr>
    <tr>
        <td>Meeting 2021</td><td><button button-type="submit">click</button></td>
    </tr>
    <tr>
        <td>Meeting 2020</td><td><button2 button-type="submit" button-text="CANCELLED"></button2></td>
    </tr>
</table>


@*Since each button shares the same type, we can use a tag helper:*@

@*Register tag helpers to use*@
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, MeetingApp


@*There are built-in tag helpers such as:

asp-controller: specifies the name of the route that will be used to generate the URL
asp-route: specifies the controller that the URL will target
asp-action: specifies the action method that the URL will target


<form asp-controller="MeetingSummary" asp-action="Index" method="post">
    <button button-type="submit"></button>
</form>

<form method="post">
    <button asp-route="Custom" button-type="submit"></button>
</form>

*@

Practice1/Views/Meeting/List.cshtml
@using MeetingApp.Models
@model List<UserInfo>


@section header {
    <div id="header">
        MEETING PARTICIPANTS
    </div>
}


<table>
    <thead>
    <tr>
        <td><b>Name</b></td>
        <td><b>Attandence status</b></td>
    </tr>
    </thead>
    <tbody>
        
        @foreach(var user in Model){
            var status = user.WillAttend == true ? "Yes" : "No";
        
        <tr>
            <td>@user.Name</td>
            <td>@status</td>
            <td>
                <a href="/Meeting/Details/@user.id">Details</a> 
            </td>
        </tr>        
    }
    </tbody>

</table>

@* html table tag includes thead and body tags. 
thead tag is used to group header content while the body tag is used group the main content of the table *@

@* The <a> tag defines a hyperlink, which is used to link from one page to another. *@
@* href attribute specifies the link *@

Practice1/Views/Meeting/Register.cshtml
@model UserInfo

<h4>Attandence Form: </h4>
<main class="text-center">
<form method="post" action="/Meeting/Register" novalidate>
    <div asp-validation-summary="All" class="text-danger"> </div>
    <div class="mb-3">
        <label asp-for="Name" class="form-label">Name</label>
        <input asp-for="Name" class="form-control" name="model.Name" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>

    <div class="mb-3">
        <label asp-for="Phone" class="form-label">Phone</label>
        <input asp-for="Phone" class="form-control" name="model.Phone" />
    </div>

    <div class="mb-3">
        <label asp-for="Email" class="form-label">Email</label>
        <input asp-for="Email" class="form-control" name="model.Email" />
        <span asp-validation-for="Email" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="WillAttend" class="form-label">Will Attend</label>
        <select asp-for="WillAttend" class="form-select" name="model.WillAttend" >
            <option value="true">Yes, I will</option>
            <option value="false">No, I will not</option>
        </select>
    </div>

    <button type="submit" class="btn btn-primary">SAVE</button>
</form>
<main>



@section header {
    <div id="header">
        MEETING REGISTRATION
    </div>
}

Practice1/Views/Meeting/RegistrationThanks.cshtml
<h2> 
    Thank you for filling the form.
</h2>

@model UserInfo

<main class="text-center">
    <h1 class="h4"> Registration Status </h1>

    @if (Model.WillAttend == true){
        <p> Thanks @Model.Name, 
            There are @ViewBag.UserCount participants with you in the meeting. </p>
        <a class="btn btn-sm btn-outline-primary" href="/Meeting/List"> List Participants </a>
    }else{
        <p> @Model.Name, we are sorry hear you do not attend. </p>
        <a class="btn btn-sm btn-outline-primary" href="/Meeting/List"> List Participants </a>
    }

</main>

Practice1/Views/Shared/_Layout.cshtml
@* This file is a simple HTML document. 
The contents of other views will be inserted by the @RenderBody() expression. *@


@*<h1> this title is in Layout </h1>*@
@*<h1> Software Engineers Meeting 2024 </h1>*@
@* 
https://getbootstrap.com/docs/5.3/getting-started/download/ 
https://getbootstrap.com/docs/5.3/utilities/text/
https://getbootstrap.com/docs/4.0/components/card/
https://www.w3schools.com/html/html_layout.asp 
*@

@* Second parameter in RenderSection() determines whether the section is optional across all views *@

<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="/lib/bootstrap/css/bootstrap.min.css"/>
        <h6 class="bg-primary text-white text-center m-2 p-2">
            @RenderSection("Header", false) 
        </h6>
    </head>

    <body class="text-center">
        <div class="bg-primary text-white text-center m-2 p-2 ">
            Software Engineers Meeting 2024 
        </div>
        <div class="container text-center" style="width: 700px">
            <div class="card">
                <div class="card-body">
                    @RenderBody()
                </div>
            </div>
        </div>     
    @RenderSection("Scripts", required: false)
</body>

    <footer>
        <h6 class="bg-primary text-white text-center m-2 p-2">
            @RenderSection("Footer", false) 
        </h6>
    </footer>



</html>